/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Stéphane Agullo (https://sketchfab.com/sa3d)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/vespa-bf3699774a564ecb9671146281859b41
title: VESPA
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    GUIDON_red_0: THREE.Mesh;
    ["POIGNEE_Material_#57_0"]: THREE.Mesh;
    FREIN_chrome_0: THREE.Mesh;
    ["PHARE_Material_#72_0"]: THREE.Mesh;
    PHARE_BORD_chrome_0: THREE.Mesh;
    FREIN_chrome_0_1: THREE.Mesh;
    ["POIGNEE_Material_#57_0_1"]: THREE.Mesh;
    CADRAN_chrome_0: THREE.Mesh;
    ["KM_Material_#86_0"]: THREE.Mesh;
    Box003_fer_0: THREE.Mesh;
    Cylinder007_fer_0: THREE.Mesh;
    Spring001_chrome_0: THREE.Mesh;
    Cylinder009_fer_0: THREE.Mesh;
    Cylinder008_fer_0: THREE.Mesh;
    ["Line001_Material_#57_0"]: THREE.Mesh;
    DECO_chrome_0: THREE.Mesh;
    VIS_chrome_0: THREE.Mesh;
    VIS_chrome_0_1: THREE.Mesh;
    BOUE_red_0: THREE.Mesh;
    VIS_chrome_0_2: THREE.Mesh;
    VIS_chrome_0_3: THREE.Mesh;
    Object004_fer_0: THREE.Mesh;
    Object005_fer_0: THREE.Mesh;
    Object006_fer_0: THREE.Mesh;
    Object007_fer_0: THREE.Mesh;
    Object008_fer_0: THREE.Mesh;
    Object009_fer_0: THREE.Mesh;
    Object010_fer_0: THREE.Mesh;
    Object011_fer_0: THREE.Mesh;
    Object012_fer_0: THREE.Mesh;
    Object013_fer_0: THREE.Mesh;
    Object014_fer_0: THREE.Mesh;
    ["Tube003_Material_#71_0"]: THREE.Mesh;
    ["Tube003_Material_#57_0"]: THREE.Mesh;
    ["Tube003_Material_#59_0"]: THREE.Mesh;
    Object003_fer_0: THREE.Mesh;
    Object002_fer_0: THREE.Mesh;
    Object001_fer_0: THREE.Mesh;
    Cylinder005_GRIS_TEST_0: THREE.Mesh;
    Cylinder006_fer_0: THREE.Mesh;
    ["Tube004_Material_#71_0"]: THREE.Mesh;
    ["Tube004_Material_#57_0"]: THREE.Mesh;
    ["Tube004_Material_#59_0"]: THREE.Mesh;
    Cylinder010_GRIS_TEST_0: THREE.Mesh;
    Cylinder011_fer_0: THREE.Mesh;
    Object015_fer_0: THREE.Mesh;
    Object016_fer_0: THREE.Mesh;
    Object017_fer_0: THREE.Mesh;
    Object018_fer_0: THREE.Mesh;
    Object019_fer_0: THREE.Mesh;
    Object020_fer_0: THREE.Mesh;
    Object021_fer_0: THREE.Mesh;
    Object022_fer_0: THREE.Mesh;
    Object023_fer_0: THREE.Mesh;
    Object024_fer_0: THREE.Mesh;
    Object025_fer_0: THREE.Mesh;
    Object026_fer_0: THREE.Mesh;
    Object027_fer_0: THREE.Mesh;
    Object028_fer_0: THREE.Mesh;
    ["Capsule002_Material_#57_0"]: THREE.Mesh;
    Rectangle001_chrome_0: THREE.Mesh;
    ["Capsule001_Material_#57_0"]: THREE.Mesh;
    Cylinder014_chrome_0: THREE.Mesh;
    Sphere007_chrome_0: THREE.Mesh;
    Sphere008_chrome_0: THREE.Mesh;
    Sphere009_chrome_0: THREE.Mesh;
    Sphere010_chrome_0: THREE.Mesh;
    Sphere011_chrome_0: THREE.Mesh;
    Sphere012_chrome_0: THREE.Mesh;
    Sphere013_chrome_0: THREE.Mesh;
    Sphere014_chrome_0: THREE.Mesh;
    BARRE_chrome_0: THREE.Mesh;
    BARRE_chrome_0_1: THREE.Mesh;
    TUBES_chrome_0: THREE.Mesh;
    ["TAPIS_Material_#57_0"]: THREE.Mesh;
    ["LANIERE_Material_#57_0"]: THREE.Mesh;
    ["GRIP_Material_#57_0"]: THREE.Mesh;
    ["GRIP_Material_#57_0_1"]: THREE.Mesh;
    ["JOINT_Material_#57_0"]: THREE.Mesh;
    ["JOINT_Material_#57_0_1"]: THREE.Mesh;
    BORDURE_chrome_0: THREE.Mesh;
    FEUX_chrome_0: THREE.Mesh;
    ["FEUX_Material_#85_0"]: THREE.Mesh;
    ["FEUX_Material_#84_0"]: THREE.Mesh;
    ["SELLE_Material_#57_0"]: THREE.Mesh;
    ["PIEDS_Material_#57_0"]: THREE.Mesh;
    MARCHE_PIEDS_chrome_0: THREE.Mesh;
    ["PIEDS_Material_#57_0_1"]: THREE.Mesh;
    MARCHE_PIEDS_chrome_0_1: THREE.Mesh;
    ["MOTEUR_Material_#57_0"]: THREE.Mesh;
    SCOOT_red_0: THREE.Mesh;
  };
  materials: {
    material: THREE.MeshPhysicalMaterial;
    Material_57: THREE.MeshPhysicalMaterial;
    chrome: THREE.MeshStandardMaterial;
    Material_72: THREE.MeshPhysicalMaterial;
    Material_86: THREE.MeshStandardMaterial;
    material_5: THREE.MeshStandardMaterial;
    Material_71: THREE.MeshStandardMaterial;
    Material_59: THREE.MeshStandardMaterial;
    GRIS_TEST: THREE.MeshStandardMaterial;
    Material_85: THREE.MeshStandardMaterial;
    Material_84: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF("/vespa.glb") as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null} >
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[35.6, 31.8, 73]} rotation={[-1.6, -0.2, 2.8]}>
            <mesh
              geometry={nodes.GUIDON_red_0.geometry}
              material={nodes.GUIDON_red_0.material}
            />
          </group>
          <group position={[-21.1, 94.7, 14.1]} rotation={[-0.3, 0.2, 0.9]}>
            <mesh
              geometry={nodes["POIGNEE_Material_#57_0"].geometry}
              material={nodes["POIGNEE_Material_#57_0"].material}
            />
          </group>
          <group position={[-16.5, 96.8, 10]} rotation={[-0.3, 0.2, 0.9]}>
            <mesh
              geometry={nodes.FREIN_chrome_0.geometry}
              material={nodes.FREIN_chrome_0.material}
            />
          </group>
          <group position={[-4.7, 102.5, -9.1]} rotation={[0, 0.2, -0.3]}>
            <mesh
              geometry={nodes["PHARE_Material_#72_0"].geometry}
              material={materials.Material_72}
            />
          </group>
          <group position={[-4.3, 102.5, -7.8]} rotation={[0, 0.2, -0.3]}>
            <mesh
              geometry={nodes.PHARE_BORD_chrome_0.geometry}
              material={nodes.PHARE_BORD_chrome_0.material}
            />
          </group>
          <group position={[16.7, 103.5, -0.6]} rotation={[-3.1, 0, -1.5]}>
            <mesh
              geometry={nodes.FREIN_chrome_0_1.geometry}
              material={nodes.FREIN_chrome_0_1.material}
            />
          </group>
          <group position={[23.2, 103.7, 0]} rotation={[-3.1, 0, -1.5]}>
            <mesh
              geometry={nodes["POIGNEE_Material_#57_0_1"].geometry}
              material={nodes["POIGNEE_Material_#57_0_1"].material}
            />
          </group>
          <group position={[-0.6, 104.4, 5]} rotation={[-2, 0.2, -0.3]}>
            <mesh
              geometry={nodes.CADRAN_chrome_0.geometry}
              material={nodes.CADRAN_chrome_0.material}
            />
          </group>
          <group position={[-0.7, 105, 5.3]} rotation={[-2, 0.2, -0.3]}>
            <mesh
              geometry={nodes["KM_Material_#86_0"].geometry}
              material={materials.Material_86}
            />
          </group>
          <group position={[-8.4, 24.5, -37.9]} rotation={[2.9, -0.7, 1.1]}>
            <mesh
              geometry={nodes.Box003_fer_0.geometry}
              material={nodes.Box003_fer_0.material}
            />
          </group>
          <group position={[0.5, 21.7, -34.8]} rotation={[3, 0, 1.3]}>
            <mesh
              geometry={nodes.Cylinder007_fer_0.geometry}
              material={nodes.Cylinder007_fer_0.material}
            />
          </group>
          <group position={[-6.1, 25.2, -36.6]} rotation={[-1.4, 0.4, -2]}>
            <mesh
              geometry={nodes.Spring001_chrome_0.geometry}
              material={nodes.Spring001_chrome_0.material}
            />
          </group>
          <group position={[-8.3, 42, -32]} rotation={[2.2, -0.2, 2.8]}>
            <mesh
              geometry={nodes.Cylinder009_fer_0.geometry}
              material={nodes.Cylinder009_fer_0.material}
            />
          </group>
          <group position={[-7.5, 29.6, -42.9]} rotation={[3, 0, 1.3]}>
            <mesh
              geometry={nodes.Cylinder008_fer_0.geometry}
              material={nodes.Cylinder008_fer_0.material}
            />
          </group>
          <group position={[-8.5, 31.5, -39.4]} rotation={[-3, 0, -1.9]}>
            <mesh
              geometry={nodes["Line001_Material_#57_0"].geometry}
              material={nodes["Line001_Material_#57_0"].material}
            />
          </group>
          <group position={[1.4, 36.8, -31.4]} rotation={[1.9, -0.2, 2.8]}>
            <mesh
              geometry={nodes.DECO_chrome_0.geometry}
              material={nodes.DECO_chrome_0.material}
            />
          </group>
          <group position={[11.1, 47.5, -29.8]} rotation={[-2.7, 0, -1.8]}>
            <mesh
              geometry={nodes.VIS_chrome_0.geometry}
              material={nodes.VIS_chrome_0.material}
            />
          </group>
          <group position={[13.1, 44.6, -25.4]} rotation={[-2.7, 0, -1.7]}>
            <mesh
              geometry={nodes.VIS_chrome_0_1.geometry}
              material={nodes.VIS_chrome_0_1.material}
            />
          </group>
          <group position={[1.4, 36.8, -31.4]} rotation={[1.9, -0.2, 2.8]}>
            <mesh
              geometry={nodes.BOUE_red_0.geometry}
              material={nodes.BOUE_red_0.material}
            />
          </group>
          <group position={[-8.8, 43.5, -23.5]} rotation={[0.1, 0, 1.2]}>
            <mesh
              geometry={nodes.VIS_chrome_0_2.geometry}
              material={nodes.VIS_chrome_0_2.material}
            />
          </group>
          <group position={[-6.8, 40.6, -19.1]} rotation={[0.1, 0.1, 1]}>
            <mesh
              geometry={nodes.VIS_chrome_0_3.geometry}
              material={nodes.VIS_chrome_0_3.material}
            />
          </group>
          <group position={[3.5, 22.3, -35.7]} rotation={[-0.2, -0.4, 1.2]}>
            <mesh
              geometry={nodes.Object004_fer_0.geometry}
              material={nodes.Object004_fer_0.material}
            />
          </group>
          <group position={[3.5, 22.3, -35.7]} rotation={[-0.2, 0.5, 1.4]}>
            <mesh
              geometry={nodes.Object005_fer_0.geometry}
              material={nodes.Object005_fer_0.material}
            />
          </group>
          <group position={[3.5, 22.3, -35.7]} rotation={[-0.8, 1.3, 2]}>
            <mesh
              geometry={nodes.Object006_fer_0.geometry}
              material={nodes.Object006_fer_0.material}
            />
          </group>
          <group position={[3.5, 22.3, -35.7]} rotation={[-2.9, 0.8, -2.1]}>
            <mesh
              geometry={nodes.Object007_fer_0.geometry}
              material={nodes.Object007_fer_0.material}
            />
          </group>
          <group position={[2.6, 22.1, -35.5]} rotation={[-0.2, 0, 1.3]}>
            <mesh
              geometry={nodes.Object008_fer_0.geometry}
              material={nodes.Object008_fer_0.material}
            />
          </group>
          <group position={[2.6, 22.1, -35.5]} rotation={[-0.3, 0.9, 1.5]}>
            <mesh
              geometry={nodes.Object009_fer_0.geometry}
              material={nodes.Object009_fer_0.material}
            />
          </group>
          <group position={[2.6, 22.1, -35.5]} rotation={[-2.5, 1.2, -2.5]}>
            <mesh
              geometry={nodes.Object010_fer_0.geometry}
              material={nodes.Object010_fer_0.material}
            />
          </group>
          <group position={[2.6, 22.1, -35.5]} rotation={[-2.9, 0.4, -2]}>
            <mesh
              geometry={nodes.Object011_fer_0.geometry}
              material={nodes.Object011_fer_0.material}
            />
          </group>
          <group position={[2.6, 22.1, -35.5]} rotation={[-2.9, -0.5, -1.8]}>
            <mesh
              geometry={nodes.Object012_fer_0.geometry}
              material={nodes.Object012_fer_0.material}
            />
          </group>
          <group position={[2.6, 22.1, -35.5]} rotation={[-2.3, -1.3, -1.1]}>
            <mesh
              geometry={nodes.Object013_fer_0.geometry}
              material={nodes.Object013_fer_0.material}
            />
          </group>
          <group position={[2.6, 22.1, -35.5]} rotation={[-0.3, -0.8, 1]}>
            <mesh
              geometry={nodes.Object014_fer_0.geometry}
              material={nodes.Object014_fer_0.material}
            />
          </group>
          <group position={[3, 22.2, -35.6]} rotation={[-3, 0, -1.9]}>
            <mesh
              geometry={nodes["Tube003_Material_#71_0"].geometry}
              material={nodes["Tube003_Material_#71_0"].material}
            />
            <mesh
              geometry={nodes["Tube003_Material_#57_0"].geometry}
              material={nodes["Tube003_Material_#57_0"].material}
            />
            <mesh
              geometry={nodes["Tube003_Material_#59_0"].geometry}
              material={nodes["Tube003_Material_#59_0"].material}
            />
          </group>
          <group position={[3.5, 22.3, -35.7]} rotation={[-0.6, -1.2, 0.7]}>
            <mesh
              geometry={nodes.Object003_fer_0.geometry}
              material={nodes.Object003_fer_0.material}
            />
          </group>
          <group position={[3.5, 22.3, -35.7]} rotation={[-2.8, -0.9, -1.6]}>
            <mesh
              geometry={nodes.Object002_fer_0.geometry}
              material={nodes.Object002_fer_0.material}
            />
          </group>
          <group position={[3.5, 22.3, -35.7]} rotation={[-3, 0, -1.9]}>
            <mesh
              geometry={nodes.Object001_fer_0.geometry}
              material={nodes.Object001_fer_0.material}
            />
          </group>
          <group position={[3.5, 22.3, -35.7]} rotation={[-3, 0, -1.9]}>
            <mesh
              geometry={nodes.Cylinder005_GRIS_TEST_0.geometry}
              material={nodes.Cylinder005_GRIS_TEST_0.material}
            />
          </group>
          <group position={[2.6, 22.1, -35.5]} rotation={[-0.2, 0, 1.3]}>
            <mesh
              geometry={nodes.Cylinder006_fer_0.geometry}
              material={nodes.Cylinder006_fer_0.material}
            />
          </group>
          <group position={[-7.4, 22.2, 85]} rotation={[Math.PI, 0, -1.5]}>
            <mesh
              geometry={nodes["Tube004_Material_#71_0"].geometry}
              material={nodes["Tube004_Material_#71_0"].material}
            />
            <mesh
              geometry={nodes["Tube004_Material_#57_0"].geometry}
              material={nodes["Tube004_Material_#57_0"].material}
            />
            <mesh
              geometry={nodes["Tube004_Material_#59_0"].geometry}
              material={nodes["Tube004_Material_#59_0"].material}
            />
          </group>
          <group position={[-6.9, 22.2, 85.1]} rotation={[Math.PI, 0, -1.5]}>
            <mesh
              geometry={nodes.Cylinder010_GRIS_TEST_0.geometry}
              material={nodes.Cylinder010_GRIS_TEST_0.material}
            />
          </group>
          <group position={[-7.9, 22.2, 85]} rotation={[0, 0, 1.7]}>
            <mesh
              geometry={nodes.Cylinder011_fer_0.geometry}
              material={nodes.Cylinder011_fer_0.material}
            />
          </group>
          <group position={[-6.9, 22.2, 85.1]} rotation={[Math.PI, 0, -1.5]}>
            <mesh
              geometry={nodes.Object015_fer_0.geometry}
              material={nodes.Object015_fer_0.material}
            />
          </group>
          <group position={[-6.9, 22.2, 85.1]} rotation={[Math.PI, -0.9, -1.5]}>
            <mesh
              geometry={nodes.Object016_fer_0.geometry}
              material={nodes.Object016_fer_0.material}
            />
          </group>
          <group position={[-6.9, 22.2, 85.1]} rotation={[0, -1.3, 1.7]}>
            <mesh
              geometry={nodes.Object017_fer_0.geometry}
              material={nodes.Object017_fer_0.material}
            />
          </group>
          <group
            position={[-6.9, 22.2, 85.1]}
            rotation={[0, -Math.PI / 7, 1.7]}
          >
            <mesh
              geometry={nodes.Object018_fer_0.geometry}
              material={nodes.Object018_fer_0.material}
            />
          </group>
          <group position={[-6.9, 22.2, 85.1]} rotation={[0, Math.PI / 7, 1.7]}>
            <mesh
              geometry={nodes.Object019_fer_0.geometry}
              material={nodes.Object019_fer_0.material}
            />
          </group>
          <group position={[-6.9, 22.2, 85.1]} rotation={[0, 1.3, 1.7]}>
            <mesh
              geometry={nodes.Object020_fer_0.geometry}
              material={nodes.Object020_fer_0.material}
            />
          </group>
          <group position={[-6.9, 22.2, 85.1]} rotation={[Math.PI, 0.9, -1.5]}>
            <mesh
              geometry={nodes.Object021_fer_0.geometry}
              material={nodes.Object021_fer_0.material}
            />
          </group>
          <group position={[-7.9, 22.2, 85]} rotation={[0, 0, 1.7]}>
            <mesh
              geometry={nodes.Object022_fer_0.geometry}
              material={nodes.Object022_fer_0.material}
            />
          </group>
          <group position={[-7.9, 22.2, 85]} rotation={[0, 0.9, 1.7]}>
            <mesh
              geometry={nodes.Object023_fer_0.geometry}
              material={nodes.Object023_fer_0.material}
            />
          </group>
          <group position={[-7.9, 22.2, 85]} rotation={[-Math.PI, 1.3, -1.5]}>
            <mesh
              geometry={nodes.Object024_fer_0.geometry}
              material={nodes.Object024_fer_0.material}
            />
          </group>
          <group
            position={[-7.9, 22.2, 85]}
            rotation={[Math.PI, Math.PI / 7, -1.5]}
          >
            <mesh
              geometry={nodes.Object025_fer_0.geometry}
              material={nodes.Object025_fer_0.material}
            />
          </group>
          <group
            position={[-7.9, 22.2, 85]}
            rotation={[Math.PI, -Math.PI / 7, -1.5]}
          >
            <mesh
              geometry={nodes.Object026_fer_0.geometry}
              material={nodes.Object026_fer_0.material}
            />
          </group>
          <group position={[-7.9, 22.2, 85]} rotation={[Math.PI, -1.3, -1.5]}>
            <mesh
              geometry={nodes.Object027_fer_0.geometry}
              material={nodes.Object027_fer_0.material}
            />
          </group>
          <group position={[-7.9, 22.2, 85]} rotation={[0, -0.9, 1.7]}>
            <mesh
              geometry={nodes.Object028_fer_0.geometry}
              material={nodes.Object028_fer_0.material}
            />
          </group>
          <group position={[23.5, 0.2, 8.5]} rotation={[1.2, 0.1, 0.1]}>
            <mesh
              geometry={nodes["Capsule002_Material_#57_0"].geometry}
              material={nodes["Capsule002_Material_#57_0"].material}
            />
          </group>
          <group position={[-1, 12.6, 11.4]} rotation={[2.8, 0, 0.1]}>
            <mesh
              geometry={nodes.Rectangle001_chrome_0.geometry}
              material={nodes.Rectangle001_chrome_0.material}
            />
          </group>
          <group position={[-24.6, 0.2, 4.3]} rotation={[-2, -0.1, 0]}>
            <mesh
              geometry={nodes["Capsule001_Material_#57_0"].geometry}
              material={nodes["Capsule001_Material_#57_0"].material}
            />
          </group>
          <group position={[2.1, 62.4, -23.5]} rotation={[-2.7, 0, -3.1]}>
            <mesh
              geometry={nodes.Cylinder014_chrome_0.geometry}
              material={nodes.Cylinder014_chrome_0.material}
            />
          </group>
          <group position={[1.9, 65.9, -22.3]} rotation={[-2.4, -0.6, -2.6]}>
            <mesh
              geometry={nodes.Sphere007_chrome_0.geometry}
              material={nodes.Sphere007_chrome_0.material}
            />
          </group>
          <group position={[4.6, 65, -22.5]} rotation={[-2.6, 0, -3]}>
            <mesh
              geometry={nodes.Sphere008_chrome_0.geometry}
              material={nodes.Sphere008_chrome_0.material}
            />
          </group>
          <group position={[5.8, 62.7, -23.6]} rotation={[-2.5, 0.7, 2.9]}>
            <mesh
              geometry={nodes.Sphere009_chrome_0.geometry}
              material={nodes.Sphere009_chrome_0.material}
            />
          </group>
          <group position={[4.8, 60.3, -24.9]} rotation={[-1.5, 1.2, 1.6]}>
            <mesh
              geometry={nodes.Sphere010_chrome_0.geometry}
              material={nodes.Sphere010_chrome_0.material}
            />
          </group>
          <group position={[2.2, 59.3, -25.5]} rotation={[-0.5, 0.7, 0.4]}>
            <mesh
              geometry={nodes.Sphere011_chrome_0.geometry}
              material={nodes.Sphere011_chrome_0.material}
            />
          </group>
          <group position={[-0.4, 60.3, -25.2]} rotation={[-0.4, 0, 0]}>
            <mesh
              geometry={nodes.Sphere012_chrome_0.geometry}
              material={nodes.Sphere012_chrome_0.material}
            />
          </group>
          <group position={[-1.6, 62.6, -24.2]} rotation={[-0.6, -0.7, -0.4]}>
            <mesh
              geometry={nodes.Sphere013_chrome_0.geometry}
              material={nodes.Sphere013_chrome_0.material}
            />
          </group>
          <group position={[-0.6, 65, -22.9]} rotation={[-1.5, -1, -1.5]}>
            <mesh
              geometry={nodes.Sphere014_chrome_0.geometry}
              material={nodes.Sphere014_chrome_0.material}
            />
          </group>
          <group position={[15.8, 40.3, 71.9]} rotation={[0, 0, -1.5]}>
            <mesh
              geometry={nodes.BARRE_chrome_0.geometry}
              material={nodes.BARRE_chrome_0.material}
            />
          </group>
          <group position={[-28, 40.3, 68.1]} rotation={[Math.PI, 0, 1.7]}>
            <mesh
              geometry={nodes.BARRE_chrome_0_1.geometry}
              material={nodes.BARRE_chrome_0_1.material}
            />
          </group>
          <group
            position={[-6.8, 27.6, 77.7]}
            rotation={[-Math.PI / 2, 0, -3.1]}
          >
            <mesh
              geometry={nodes.TUBES_chrome_0.geometry}
              material={nodes.TUBES_chrome_0.material}
            />
          </group>
          <group
            position={[-6.8, 27.6, 77.7]}
            rotation={[-Math.PI / 2, 0, -3.1]}
          >
            <mesh
              geometry={nodes["TAPIS_Material_#57_0"].geometry}
              material={nodes["TAPIS_Material_#57_0"].material}
            />
          </group>
          <group
            position={[-5.2, 68.4, 59.6]}
            rotation={[-Math.PI / 2, 0, 0.1]}
          >
            <mesh
              geometry={nodes["LANIERE_Material_#57_0"].geometry}
              material={nodes["LANIERE_Material_#57_0"].material}
            />
          </group>
          <group
            position={[-6.8, 27.6, 77.7]}
            rotation={[Math.PI / 2, 0, -3.1]}
          >
            <mesh
              geometry={nodes["GRIP_Material_#57_0"].geometry}
              material={nodes["GRIP_Material_#57_0"].material}
            />
          </group>
          <group
            position={[-6.8, 27.6, 77.7]}
            rotation={[-Math.PI / 2, 0, -3.1]}
          >
            <mesh
              geometry={nodes["GRIP_Material_#57_0_1"].geometry}
              material={nodes["GRIP_Material_#57_0_1"].material}
            />
          </group>
          <group
            position={[-6.8, 27.6, 77.7]}
            rotation={[Math.PI / 2, 0, -3.1]}
          >
            <mesh
              geometry={nodes["JOINT_Material_#57_0"].geometry}
              material={nodes["JOINT_Material_#57_0"].material}
            />
          </group>
          <group
            position={[-6.8, 27.6, 77.7]}
            rotation={[-Math.PI / 2, 0, -3.1]}
          >
            <mesh
              geometry={nodes["JOINT_Material_#57_0_1"].geometry}
              material={nodes["JOINT_Material_#57_0_1"].material}
            />
          </group>
          <group
            position={[-6.8, 27.6, 77.7]}
            rotation={[-Math.PI / 2, 0, -3.1]}
          >
            <mesh
              geometry={nodes.BORDURE_chrome_0.geometry}
              material={nodes.BORDURE_chrome_0.material}
            />
          </group>
          <group
            position={[-8.9, 47.9, 104.5]}
            rotation={[-Math.PI / 2, 0, 0.1]}
          >
            <mesh
              geometry={nodes.FEUX_chrome_0.geometry}
              material={nodes.FEUX_chrome_0.material}
            />
            <mesh
              geometry={nodes["FEUX_Material_#85_0"].geometry}
              material={materials.Material_85}
            />
            <mesh
              geometry={nodes["FEUX_Material_#84_0"].geometry}
              material={materials.Material_84}
            />
          </group>
          <group
            position={[-5.3, 68.4, 60.7]}
            rotation={[-Math.PI / 2, 0, 0.1]}
          >
            <mesh
              geometry={nodes["SELLE_Material_#57_0"].geometry}
              material={nodes["SELLE_Material_#57_0"].material}
            />
          </group>
          <group position={[20.7, 31.5, 57.3]} rotation={[3.1, -0.1, -1.5]}>
            <mesh
              geometry={nodes["PIEDS_Material_#57_0"].geometry}
              material={nodes["PIEDS_Material_#57_0"].material}
            />
          </group>
          <group position={[6.3, 19.6, 79.2]} rotation={[Math.PI / 2, 0, 0.1]}>
            <mesh
              geometry={nodes.MARCHE_PIEDS_chrome_0.geometry}
              material={nodes.MARCHE_PIEDS_chrome_0.material}
            />
          </group>
          <group position={[-30.3, 31.5, 52.9]} rotation={[0, 0.1, 1.7]}>
            <mesh
              geometry={nodes["PIEDS_Material_#57_0_1"].geometry}
              material={nodes["PIEDS_Material_#57_0_1"].material}
            />
          </group>
          <group position={[-20, 19.6, 76.9]} rotation={[-Math.PI / 2, 0, 0.1]}>
            <mesh
              geometry={nodes.MARCHE_PIEDS_chrome_0_1.geometry}
              material={nodes.MARCHE_PIEDS_chrome_0_1.material}
            />
          </group>
          <group position={[-13, 33.6, 76.7]} rotation={[-Math.PI, 0, 1.7]}>
            <mesh
              geometry={nodes["MOTEUR_Material_#57_0"].geometry}
              material={nodes["MOTEUR_Material_#57_0"].material}
            />
          </group>
          <group
            position={[-6.8, 27.6, 77.7]}
            rotation={[-Math.PI / 2, 0, -3.1]}
          >
            <mesh
              geometry={nodes.SCOOT_red_0.geometry}
              material={nodes.SCOOT_red_0.material}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/vespa.glb");
